[[pages]]
path = "pages/home.py"
name = "HOME"
icon = "ğŸ "

[[pages]]
path = "pages/app_dalle.py"
name = "DALL-E"
icon = ":lower_left_paintbrush:"

[[pages]]
path = "pages/app_gpt.py"
name = "GPT"
icon = ":robot_face:"

[[pages]]
path = "pages/app_tts.py"
name = "TTS"
icon = ":microphone:"